[package]
name = "garden-bevy"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
garden-domain.workspace = true
garden-application.workspace = true
garden-generation.workspace = true
bevy_app.workspace = true
bevy_ecs.workspace = true
bevy_tasks.workspace = true

[dev-dependencies]
garden-geometry.workspace = true
